apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # Make our demo user alice part of team-a
  policy.csv: |
    g, robbie, role:readonly
    g, alice, proj:team-a:read-only

  # All sso users get atleast this role
  policy.default: role:readonly
