apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  # Make our demo users alice and bob part of team-a and team-b respectively
  # Bob will take the read-write role for team-b
  policy.csv: |
    g, robbie, role:readonly
    g, alice, proj:team-a:read-only
    g, bob, proj:team-b:read-write
